######################################################################
#####                  以下配置为论坛所用到服务的一些配置,可不填.        #####
#####                     但是为了您的用户的体验,推荐将其完善           #####
######################################################################
bbs:
  # 论坛链接
  url: http://localhost:60030
  mail:
    # 邮件标题
    title: 氢论坛---邮件通知

  github:
    id: 08b076ae3cf904cf324c
    secret: 09c5129c5e0ff8b3284adbc7ae8031fe3ea04af3
  user:
    # 默认用户信息
    default:
      # 用户头像链接
      avatar-url: https://alicdn.bestsort.cn/icon/default.jpeg
      # 用户简介
      bio: 这人太懒了,没有留下简介
      # 用户昵称
      nickname: 无名氏
  encryption:
    # 加密种子,主要用于加密.为int范围的整数
    seed: 0x3f2a3c7e
    # 盐值,用于user表密码加密,字符串推荐长度>3
    salt: xzcawx

  # 阿里云OSS,用于存储用户发布时上传的图片.如无图片上传需求可不填
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    #阿里云主账号AccessKey拥有所有API的访问权限，风险很高。
    #强烈建议您创建并使用RAM账号进行API访问或日常运维，请登录 https://ram.console.aliyun.com 创建RAM账号
    accessKeyId: LTAI4FqQKcwNokbjvdqrr3xb
    accessKeySecret: YqLF8HLVkR8n1LN7ZJwAssj6WPjvgO
    bucketName: bbs-bestsort-cn
    #<yourObjectName>上传文件到OSS时需要指定包含文件后缀在内的完整路径，例如abc/efg/123.jpg。
    objectName: bbs
    #回源链接前半部分.需要在阿里云OSS指定域名,否则直接访问链接会变成下载资源
    callbackUrl: http://bbscdn.bestsort.cn

spring:
  # 邮件,用于通知/用户注册,默认使用SSL加密
  mail:
    host: smtp.exmail.qq.com
    port: 465
    username: no-reply@mail.bestsort.cn
    password: nfNHVYBwXYWNHUsd

######################################################################
#####                 以下为默认配置,如非必要不用修改                  #####
######################################################################
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
            required: true

######################################################################
#####                   请确认数据库字符编码为:utf8m4                #####
######################################################################

  datasource:
    url: '@jdbc.url@'
    username: '@jdbc.user@'
    password: '@jdbc.passwd@'
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
      filters:  stat,wall
      aop-patterns:
        - cn.bestsort.bbslite.service.*
        - cn.bestsort.bbslite.manager.*
    redis:
      # redis数据库索引（默认为0），我们使用索引为3的数据库，避免和其他数据库冲突
      database: 0
      # redis服务器地址（默认为localhost）
      host: localhost
      # redis端口（默认为6379）
      port: 6379
      # redis访问密码（默认为空）
      password:
      # redis连接超时时间（单位为毫秒）
      timeout: 20
      # redis连接池配置
      pool:
        # 最大可用连接数（默认为8，负数表示无限）
        max-active: 8
        # 最大空闲连接数（默认为8，负数表示无限）
        max-idle: 8
        # 最小空闲连接数（默认为0，该值只有为正数才有作用）
        min-idle: 0
        # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
        max-wait: -1
logging:
  file: log/bbs-lite.log
  level:
    root: info
    cn.bestsort.bbslite.cache: debug
mybatis:
  type-aliases-package: cn.bestsort.bbslite.mapper
  configuration.map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
server:
  servlet:
    session:
      timeout: 15552000
  address: 0.0.0.0
  port: 60030
